/*
    Find a string in a list of documents using Divide and Conquer with ForkJoinPool
 */
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ForkJoinPool;

public class Main {

    public static void main(String[] args){
        String macbeth = "Macbeth Summary. \n" +
                "Macbeth is a tragedy by William Shakespeare about a Scottish general consumed by unchecked ambition. Urged by his wife, he murders King Duncan to seize the throne, descends into paranoia and tyranny, and is ultimately defeated in a rebellion sparked by his murderous reign.The Prophecy and the PlotAfter a victorious battle, generals Macbeth and Banquo encounter three witches. The witches prophesy that Macbeth will become Thane of Cawdor and eventually King of Scotland, and that Banquo's descendants will inherit the throne. Shortly after, Macbeth is officially named Thane of Cawdor, making the first part of the prophecy a reality. Spurred by the news and his wife's ambition, Macbeth murders King Duncan while the King is a guest at their castle.Reign of TerrorMacbeth is crowned king, but he and his wife are immediately plagued by guilt and paranoia. To eliminate threats to his power, Macbeth hires murderers to kill Banquo and his son, Fleance. Banquo is murdered, but Fleance escapes. At a royal banquet, Macbeth is haunted by Banquo’s ghost, confirming the Scottish nobles' suspicions that Macbeth is a ruthless tyrant.DownfallDesperate for answers, Macbeth visits the witches again, who offer him three new prophecies: he must beware Macduff, no man born of a woman can harm him, and he is safe until Birnam Wood moves to Dunsinane Hill. Confident in his invincibility, Macbeth orders the slaughter of Macduff's entire family. Meanwhile, a guilt-ridden Lady Macbeth goes mad and eventually dies by suicide. Macduff joins forces with Duncan's exiled son, Malcolm, to raise an English army. They disguise their troops with branches from Birnam Wood and march on Macbeth's castle. In the final battle, Macduff reveals he was born by Caesarean section (\"untimely ripped\"), fulfilling the witches' warning. Macduff slays Macbeth, and Malcolm becomes the rightful King of Scotland.";
        String hamlet = "Hamlet Summary. \n" +
                "Prince Hamlet seeks to avenge his murdered father. After feigning madness and confirming his uncle Claudius's guilt, Hamlet accidentally kills the advisor Polonius. This sparks a tragic chain of events ending in a poisoned fencing match where Hamlet, Claudius, Gertrude, and Laertes all perish.Key Plot PointsThe Ghost's Revelation: Prince Hamlet returns to Denmark to mourn his father's death. His father's ghost appears, revealing that Claudius (Hamlet’s uncle) murdered him with poison and demanding revenge. Hamlet decides to feign madness to investigate.The Play-within-a-Play: Consumed by doubt and hesitation, Hamlet hires traveling actors to perform a scene mimicking his father's murder. Claudius's panicked reaction confirms his guilt to Hamlet.The Accidental Murder: When confronting his mother, Gertrude, Hamlet hears someone eavesdropping behind a tapestry. Believing it to be the King, Hamlet strikes through the curtain and kills Polonius.Rising Tensions: Hamlet is banished to England. Driven mad by her father's death, Ophelia—Hamlet’s former love—drowns. Her brother Laertes returns to Denmark seeking revenge.The Poisoned Duel: Claudius and Laertes conspire to eliminate Hamlet. They arrange a fencing match, utilizing a poisoned blade and a poisoned cup of wine. During the chaotic duel, Gertrude accidentally drinks the poisoned wine. Both Hamlet and Laertes are struck by the tainted blade. Before dying, Hamlet finally kills Claudius.";
        String othello = "Othello Summary. \n" +
                "William Shakespeare's Othello (circa 1603) is a tragic play about Othello, a Moorish military general. Manipulated by his envious ensign, Iago, into believing his wife, Desdemona, is unfaithful with his lieutenant, Michael Cassio, Othello is consumed by jealous rage. This ultimately drives him to murder Desdemona and subsequently take his own life.Venice: The Spark of BetrayalThe play begins in Venice with Iago plotting against Othello, who recently promoted Cassio to lieutenant over Iago. Seeking revenge, Iago manipulates Roderigo, a wealthy gentleman in love with Desdemona, and helps him alert Desdemona's father, Senator Brabantio, that his daughter has secretly eloped with Othello. When confronted before the Venetian Senate, both Othello and Desdemona defend their love, and the Senate allows their marriage to stand.Cyprus: Iago's Plot UnfoldsOthello, Desdemona, and Iago travel to Cyprus to defend the island against the Turkish fleet. Once there, Iago orchestrates a drunken brawl to get Cassio demoted, and then persuades Cassio to ask Desdemona to help him regain his position. Iago uses this interaction to plant seeds of doubt in Othello's mind, making it appear that Desdemona and Cassio are having an illicit affair.The Handkerchief and the ClimaxIago's deceit intensifies when he steals Desdemona's prized handkerchief—her first gift from Othello—and places it in Cassio's possession. Seeing Cassio with the handkerchief serves as \"proof\" for Othello, solidifying his belief in his wife's infidelity. Consumed by jealousy, Othello orders Iago to kill Cassio and strangles Desdemona in her bed.Tragic ResolutionFollowing Desdemona's death, Iago's wife Emilia reveals that Iago had manipulated them all and that Desdemona was completely innocent. In overwhelming grief and realization of his catastrophic mistake, Othello stabs Iago and then kills himself to lie beside his wife. The play ends with Iago being arrested and taken away for punishment.";
        String illiad = "Illiad Summary. \n" +
                "AI Overview Homer's The Iliad covers a few dramatic weeks during the final year of the decade-long Trojan War. It focuses on the rage of the Greek champion Achilles, his withdrawal from battle after being dishonored by King Agamemnon, and his eventual vengeful return to duel the Trojan prince Hector.The Rage of AchillesIn the ninth year of the Trojan War, the Greek (Achaean) leader Agamemnon and the warrior Achilles quarrel over captive women. Agamemnon takes Achilles' prized captive, Briseis, as compensation for losing his own. Deeply insulted, Achilles withdraws from the fighting and asks his mother, the sea-goddess Thetis, to have Zeus help the Trojans so the Greeks will realize how much they need him.Trojan AdvanceWithout Achilles, the Greeks suffer massive defeats. The Trojan prince Hector pushes the Greek forces all the way back to their ships, even setting some on fire. Desperate to save the Greek camp, Achilles' close friend Patroclus begs to wear Achilles' armor and lead the Myrmidons into battle. Patroclus successfully drives the Trojans back but is eventually killed in combat by Hector, who strips him of the armor.Vengeance and ResolutionDevastated and enraged by his friend's death, Achilles reconciles with Agamemnon and returns to the battlefield wearing a new set of divine armor forged by Hephaestus. He slaughters countless Trojans before facing Hector outside the gates of Troy. Achilles kills Hector, desecrates his corpse, and drags it behind his chariot. The poem concludes with Hector's father, King Priam, secretly visiting Achilles' tent to beg for his son's body. Moved by the old king's grief, Achilles relents, and the epic ends with Hector receiving a proper funeral in Troy.";
        String odyssey = "Odyssey Summary. \n" +
                "Homer's The Odyssey is an ancient Greek epic poem following the heroic king Odysseus of Ithaca on a perilous ten-year journey home after the Trojan War. Plagued by monstrous obstacles and presumed dead, he fights to reclaim his kingdom, reunite with his wife Penelope, and restore order.The narrative can be divided into three core acts:1. The Situation in IthacaTwenty years after departing for the Trojan War, Odysseus has not returned. His palace has been overrun by rowdy suitors, a group of powerful young men who are draining his estate and aggressively pressuring his loyal wife, Penelope, to marry one of them. Meanwhile, Odysseus's son, Telemachus, feels helpless to stop them. With the encouragement of the goddess Athena, Telemachus sets sail to gather news of his father, while Penelope desperately stalls the suitors by tricking them with a woven funeral shroud.2. Odysseus's TravelsThe poem flashes back to chronicle Odysseus's adventures over the past ten years. Stranded for years on the island of the nymph Calypso, he is finally allowed to leave by order of the gods. After a storm orchestrated by his enemy, the sea god Poseidon, he washes up on the island of Phaeacia. There, he recounts his harrowing backstory to the king. His legendary journey includes:The Cyclops: Blinding the one-eyed giant Polyphemus, which earns Odysseus the wrath of Poseidon.The Sirens: Successfully navigating past the deadly, enchanting voices of the Sirens by having his men tie him to the ship's mast.Scylla and Charybdis: Passing through a dangerous strait where a six-headed monster eats six of his men, narrowly avoiding a massive, ship-destroying whirlpool.Helios's Cattle: The loss of his entire remaining crew as punishment for slaughtering the sacred cattle of the sun god Helios.3. Return and VengeanceOnce Odysseus finishes his tale, the Phaeacians help transport him home to Ithaca. Disguised as an old beggar by Athena to avoid assassination, he reunites with his son, Telemachus, and a few loyal servants. Back at the palace, Penelope tests the suitors by challenging them to string Odysseus's great bow and shoot an arrow through a line of axe heads—a task only the true king can accomplish. When none of them can do it, Odysseus steps forward, reveals his identity, and alongside his son, slaughters the suitors. He ultimately proves his identity to Penelope by revealing the secret construction of their marriage bed, finally restoring peace to his kingdom.";

        List<String> documents = List.of(macbeth,hamlet,othello,illiad,odyssey);
        String needle = "king";
        ForkJoinPool forkJoinPool = ForkJoinPool.commonPool();
        Map<Integer, List<Integer>> foundIndicesMap = new HashMap<>();
        for(int i=0;i<documents.size();i++){
            SearchTask task = new SearchTask(i,documents.get(i),needle,0,documents.get(i).length()-1);
            List<Integer> result = forkJoinPool.invoke(task);
            foundIndicesMap.put(i, result);
        }

        for(int idx : foundIndicesMap.keySet()){
            System.out.println("Document index: "+idx+" needle "+needle+ " found at "+foundIndicesMap.get(idx).toString());
        }

        System.out.println(odyssey.substring(89, 93));
        System.out.println(odyssey.substring(246, 250));
        System.out.println(odyssey.substring(855, 859));
        System.out.println(odyssey.substring(1257, 1261));

    }
}
